//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEgitimAkademiPortfolioo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int CareerId { get; set; }
        public string CareerName { get; set; }
        public string CareerDescription { get; set; }
        public Nullable<int> CareerWorkTime { get; set; }
    }
}
