//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEgitimAkademiPortfolioo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickContact
    {
        public int QuickContactId { get; set; }
        public string İsimSoyisim { get; set; }
        public string Resim { get; set; }
        public string Aciklama { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Behance { get; set; }
        public string Linkedin { get; set; }
        public string Facebook { get; set; }
        public string Twiter { get; set; }
    }
}
